//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanGiay_Nhom13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CHITIETHOADON = new HashSet<CHITIETHOADON>();
            this.GIOHANG = new HashSet<GIOHANG>();
            this.PHUKIEN = new HashSet<PHUKIEN>();
            this.SANPHAMNOIBAT = new HashSet<SANPHAMNOIBAT>();
            this.KHUYENMAI1 = new HashSet<KHUYENMAI>();
            this.SANPHAM_SIZE = new HashSet<SANPHAM_SIZE>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public string HINHANH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<decimal> GIA { get; set; }
        public string MOTA { get; set; }
        public string MATH { get; set; }
        public string MAL { get; set; }
        public string MAKM { get; set; }
    
        public virtual ICollection<CHITIETHOADON> CHITIETHOADON { get; set; }
        public virtual ICollection<GIOHANG> GIOHANG { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual LOAISP LOAISP { get; set; }
        public virtual ICollection<PHUKIEN> PHUKIEN { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
        public virtual ICollection<SANPHAMNOIBAT> SANPHAMNOIBAT { get; set; }
        public virtual ICollection<KHUYENMAI> KHUYENMAI1 { get; set; }
        public virtual ICollection<SANPHAM_SIZE> SANPHAM_SIZE { get; set; }
    }
}
